import {StyleSheet} from "react-native";
export const styles = StyleSheet.create({
    container: {
        color: "#000000",
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 24,
        paddingTop: 60,
    },
    title: {
        fontSize: 26,
        fontWeight: 'bold',
        textAlign: 'center',
        color: '#222222',
        marginBottom: 24,
    },
    header: {
        fontSize: 20,
        fontWeight: '600',
        textAlign: 'center',
        color: '#333333',
        marginBottom: 12,
    },
    input: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#DDDDDD',
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 16,
        fontSize: 16,
        color: '#000000',
        backgroundColor: '#FAFAFA',
        marginVertical: 10,
    },
    error: {
        marginVertical: 10,
        textAlign: 'center',
        color: '#D8000C',
        fontSize: 14,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 20,
    },
    button: {
        flex: 1,
        backgroundColor: '#3366FF',
        paddingVertical: 12,
        marginHorizontal: 6,
        borderRadius: 6,
        alignItems: 'center',
    },
    buttonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '500',
    },
    link: {
        marginTop: 16,
        fontSize: 14,
        textAlign: 'center',
        color: '#1e90ff',
    },
});

